"""
This type stub file was generated by pyright.
"""

from typing import Optional
from fastapi.concurrency import AsyncExitStack
from starlette.types import ASGIApp, Receive, Scope, Send

class AsyncExitStackMiddleware:
    def __init__(self, app: ASGIApp, context_name: str = ...) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    


