"""
This type stub file was generated by pyright.
"""

import functools
import re
import typing
from starlette.datastructures import Headers, MutableHeaders
from starlette.responses import PlainTextResponse, Response
from starlette.types import ASGIApp, Message, Receive, Scope, Send

ALL_METHODS = ...
SAFELISTED_HEADERS = ...
class CORSMiddleware:
    def __init__(self, app: ASGIApp, allow_origins: typing.Sequence[str] = ..., allow_methods: typing.Sequence[str] = ..., allow_headers: typing.Sequence[str] = ..., allow_credentials: bool = ..., allow_origin_regex: typing.Optional[str] = ..., expose_headers: typing.Sequence[str] = ..., max_age: int = ...) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    
    def is_allowed_origin(self, origin: str) -> bool:
        ...
    
    def preflight_response(self, request_headers: Headers) -> Response:
        ...
    
    async def simple_response(self, scope: Scope, receive: Receive, send: Send, request_headers: Headers) -> None:
        ...
    
    async def send(self, message: Message, send: Send, request_headers: Headers) -> None:
        ...
    
    @staticmethod
    def allow_explicit_origin(headers: MutableHeaders, origin: str) -> None:
        ...
    


