"""
This type stub file was generated by pyright.
"""

from . import platform

__all__ = ('PRISMA_CLI_NAME', )
if platform.name() == 'windows':
    PRISMA_CLI_NAME = ...
else:
    PRISMA_CLI_NAME = ...
