"""
This type stub file was generated by pyright.
"""

import ssl
import typing
import anyio
from .._exceptions import ConnectError, ConnectTimeout, ReadError, ReadTimeout, WriteError, WriteTimeout, map_exceptions
from .._utils import is_socket_readable
from .base import AsyncNetworkBackend, AsyncNetworkStream

class AsyncIOStream(AsyncNetworkStream):
    def __init__(self, stream: anyio.abc.ByteStream) -> None:
        ...
    
    async def read(self, max_bytes: int, timeout: typing.Optional[float] = ...) -> bytes:
        ...
    
    async def write(self, buffer: bytes, timeout: typing.Optional[float] = ...) -> None:
        ...
    
    async def aclose(self) -> None:
        ...
    
    async def start_tls(self, ssl_context: ssl.SSLContext, server_hostname: typing.Optional[str] = ..., timeout: typing.Optional[float] = ...) -> AsyncNetworkStream:
        ...
    
    def get_extra_info(self, info: str) -> typing.Any:
        ...
    


class AsyncIOBackend(AsyncNetworkBackend):
    async def connect_tcp(self, host: str, port: int, timeout: typing.Optional[float] = ..., local_address: typing.Optional[str] = ...) -> AsyncNetworkStream:
        ...
    
    async def connect_unix_socket(self, path: str, timeout: typing.Optional[float] = ...) -> AsyncNetworkStream:
        ...
    
    async def sleep(self, seconds: float) -> None:
        ...
    


