"""
This type stub file was generated by pyright.
"""

def flow_matrix_row(G, weight=..., dtype=..., solver=...): # -> Generator[tuple[Unknown, tuple[Unknown, Unknown]], None, None]:
    ...

class InverseLaplacian:
    def __init__(self, L, width=..., dtype=...) -> None:
        ...
    
    def init_solver(self, L): # -> None:
        ...
    
    def solve(self, r):
        ...
    
    def solve_inverse(self, r):
        ...
    
    def get_rows(self, r1, r2):
        ...
    
    def get_row(self, r):
        ...
    
    def width(self, L): # -> int:
        ...
    


class FullInverseLaplacian(InverseLaplacian):
    def init_solver(self, L): # -> None:
        ...
    
    def solve(self, rhs):
        ...
    
    def solve_inverse(self, r):
        ...
    


class SuperLUInverseLaplacian(InverseLaplacian):
    def init_solver(self, L): # -> None:
        ...
    
    def solve_inverse(self, r):
        ...
    
    def solve(self, rhs):
        ...
    


class CGInverseLaplacian(InverseLaplacian):
    def init_solver(self, L): # -> None:
        ...
    
    def solve(self, rhs):
        ...
    
    def solve_inverse(self, r):
        ...
    


