"""
This type stub file was generated by pyright.
"""

__all__ = ["assert_nodes_equal", "assert_edges_equal", "assert_graphs_equal", "almost_equal"]
def almost_equal(x, y, places=...):
    ...

def assert_nodes_equal(nodes1, nodes2): # -> None:
    ...

def assert_edges_equal(edges1, edges2): # -> None:
    ...

def assert_graphs_equal(graph1, graph2): # -> None:
    ...

