"""
This type stub file was generated by pyright.
"""

from networkx.lazy_imports import _lazy_import
from networkx.exception import *
from networkx import algorithms, classes, convert, convert_matrix, drawing, generators, linalg, readwrite, relabel, utils
from networkx.classes import filters
from networkx.convert import *
from networkx.convert_matrix import *
from networkx.relabel import *
from networkx.generators import *
from networkx.readwrite import *
from networkx.algorithms import *
from networkx.linalg import *
from networkx.testing.test import run as test
from networkx.drawing import *

"""
NetworkX
========

NetworkX is a Python package for the creation, manipulation, and study of the
structure, dynamics, and functions of complex networks.

See https://networkx.org for complete documentation.
"""
__version__ = ...
def __getattr__(name):
    """Remove functions and provide informative error messages."""
    ...

